### ISSUE TITLE
vyos_user lacking ssh key addition

### ISSUE THREAD

**Issue by archongtv** [vyos/vyos.vyos#103]
Hi,
when creating user with vyos_user I can only add user with password. There's no possibility to attach ssh key.

**Comment by nicolas-janzen** [comment]
I have found myself a workaround which suites my case:
Maybe you can get a use of that:

 - name: Set authorized keys for vyos
   vyos.vyos.vyos_config:
     lines:
       - set system login user vyos authentication public-keys {{ item.name }} key '{{ item.public_keys | regex_replace('^ssh-rsa ','') }}'
       - set system login user vyos authentication public-keys {{ item.name }} type 'ssh-rsa'
   connection: network_cli
   loop: "{{ users }}"
   when: item.state == 'present'
 
 - name: Delete authorized keys for vyos
   vyos.vyos.vyos_config:
     lines:
       - delete system login user vyos authentication public-keys {{ item.name }}
   connection: network_cli
   loop: "{{ users }}"
   when: item.state == 'absent'

**Comment by sever-sever** [comment]
I use the key from the file.
```
  - set system login user {{ ansible_user }} authentication public-keys sever@pc type ssh-rsa
  - set system login user {{ ansible_user }} authentication public-keys sever@pc key "{{ lookup('file', 'id_rsa.pub') }}"
```
And keys in files:
```
$ ls -l files/id*
-rw-r--r-- 1 sever sever 544 May 25  2022 files/id_rsa_docker.pub
-rw-r--r-- 1 sever sever 544 Jun  2  2022 files/id_rsa.pub
```
