### ISSUE TITLE
[vyos_config] Remove statements not in config

### ISSUE THREAD

**Issue by majekw** [vyos/vyos.vyos#179]
##### SUMMARY

When providing config in brace style it's translated to only 'set' statements. It's then just merged with existing config, but statements not in provided config are not deleted.
It could be good to have option to load fresh full config and delete everything else. Just like Vyos 'load' command do.

Maybe something like 'state: merge [default] or replaced' as can be found in other modules?

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

vyos_config

##### ADDITIONAL INFORMATION

We build full config using templates, then send to device to replace old config with new one. Right now we just copy this config and issue 'load' command, but using proper module with diff and report what was really send to device would be definitely more proper way of doing this.

**Comment by andamasov** [comment]
moved to vyos.dev
https://vyos.dev/T6828
