### ISSUE TITLE
[vyos_config] unable to update encrypted-password

### ISSUE THREAD

**Issue by lucaelin** [vyos/vyos.vyos#191]
##### SUMMARY
Trying to set the encrypted-password key does not work when using `vyos_config`, because of a filter on the commands to run on the target [here](https://github.com/ansible-collections/vyos.vyos/blob/main/plugins/modules/vyos_config.py#L214). 
I would like to be able to set the encrypted-password to be the same on all of my devices, without having to deal cleartext passwords in my ansible output diff. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vyos_config

##### ANSIBLE VERSION

```
ansible [core 2.11.2]
```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
vyos.vyos  2.3.0
```

##### STEPS TO REPRODUCE

```yaml
- name: render a Jinja2 template onto the VyOS router
  vyos.vyos.vyos_config:
    lines: set system login user lucaelin authentication encrypted-password '$6$saltysalt$OvwDpjWdBeANXS5VmgbxQEy9DOywsFLAZa.bBULLVgy8TFyKJBmewy0nMg5D70MysS8un40UH1DmCSf6haSMl/'
  register: output

- debug:
    var: output
```

##### EXPECTED RESULTS

The password-hash should be set on the device

##### ACTUAL RESULTS

The command is filtered

```paste below
TASK [vyos : render a Jinja2 template onto the VyOS router] ****************************************

ok: [vyos.box]

TASK [vyos : debug] ********************************************************************************
ok: [vyos.box] => {
    "output": {
        "changed": false,
        "commands": [],
        "diff": {
            "prepared": null
        },
        "failed": false,
        "filtered": [
            "set system login user lucaelin authentication encrypted-password '$6$saltysalt$OvwDpjWdBeANX
S5VmgbxQEy9DOywsFLAZa.bBULLVgy8TFyKJBmewy0nMg5D70MysS8un40UH1DmCSf6haSMl/'"
        ]
    }
}
```

**Comment by sever-sever** [comment]
It makes sense

**Comment by desultory** [comment]
I'm having the same issue, can't set it manually via the command line either

**Comment by andamasov** [comment]
Moving this to vyos.dev
https://vyos.dev/T6818
