### ISSUE TITLE
Support for dummy interfaces

### ISSUE THREAD

**Issue by lingfish** [vyos/vyos.vyos#265]
##### SUMMARY
I've done a search, and I see nowhere any mention of dummy interface support, or a request for it.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vyos.vyos.vyos_l3_interfaces

##### ADDITIONAL INFORMATION
Should be self-explanatory.

**Comment by andamasov** [comment]
moved to vyos.dev
https://vyos.dev/T6824
