### ISSUE TITLE
Add option to configure autoconf (slaac) for ipv6 interfaces

### ISSUE THREAD

**Issue by strifel** [vyos/vyos.vyos#266]
##### SUMMARY
Allow to specify `autoconf` as ip address for v6 interfaces.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
vyos_l3_interfaces

##### ADDITIONAL INFORMATION
https://docs.vyos.io/en/equuleus/configuration/interfaces/ethernet.html#cfgcmd-set-interfaces-ethernet-interface-ipv6-address-autoconf

**Comment by andamasov** [comment]
Moved to vyos.dev
https://vyos.dev/T6823
