### ISSUE TITLE
Document how to create new modules

### ISSUE THREAD

**Issue by sdwilsh** [vyos/vyos.vyos#282]
##### SUMMARY
Document how to create new modules

##### ISSUE TYPE
- Documentation Report

##### DETAILS

Most (all?) modules have some text in them that says "This file is auto generated by the resource module builder playbook.", and reference a template that should be used.  However, I don't see anything that looks like these are generated from within this repository, which makes it quite difficult to contribute new modules here.

**Comment by gaige** [comment]
These were built as documented in the [Ansible network resources](https://docs.ansible.com/ansible/latest/network/getting_started/network_resources.html).  Now that this is separately curated through vyos, we may need to consider moving this.

**Comment by gaige** [comment]
@andamasov This should be moved over to vyos.dev ; I partially did this in the `README` in a pending PR (not out of draft yet), but it doesn't specifically talk about our recommendations for *new* items.

**Comment by andamasov** [comment]
Moved to https://vyos.dev/T6887
