### ISSUE TITLE
`vyos.vyos.vyos_static_routes` does not support interface routes

### ISSUE THREAD

**Issue by sdwilsh** [vyos/vyos.vyos#283]
##### SUMMARY
There are a few issues that make supporting interface routes not possible today:
* `forward_router_address` is required, which doesn't make sense for an interface route.  For a static route you need one of `forward_router_address` or `interface`.
* Even working around that issue, the generated command only looks like it'd work for the current rolling release, and not 1.3 or older which uses a slightly different syntax.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`vyos.vyos.vyos_static_routes`

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
vyos.vyos  3.0.1  

# /home/sdwilsh/.local/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
vyos.vyos  3.0.1  

# /home/sdwilsh/ansible-collection-dev/ansible_collections
Collection Version
---------- -------
vyos.vyos  4.0.0
```

**Comment by andamasov** [comment]
moved to vyos.dev
https://vyos.dev/T6834
