### ISSUE TITLE
Move collection-level documentation into the collection

### ISSUE THREAD

**Issue by samccann** [vyos/vyos.vyos#337]
##### SUMMARY

We are moving away from having collection-specific documentation outside of a collection as they end up unmaintained.
Move the following docs inside this collection:
https://docs.ansible.com/ansible/latest/network/user_guide/platform_vyos.html

##### ISSUE TYPE
- Documentation Report

##### ANSIBLE VERSION

```paste below

```

**Comment by andamasov** [comment]
@NilashishC, how can this be handled on our side?

**Comment by samccann** [comment]
The easiest way is to add it to the collection docs/docsite directory - https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_structure.html#collections-doc-dir

This issue was opened for docs removed from the community version of Ansible. The above link goes into detail on how to do that.

NOTE: If you want these docs on Automation Hub, it's in markdown and last I checked, only supports a few files with no index to order them in.  That said, I believe Automation Hub supports having a separate docsite if you want more complete docs available there. See https://docs.ansible.com/ansible/latest/dev_guide/developing_collections_documenting.html#build-a-docsite-with-antsibull-docs for some ideas on how to do that.

**Comment by gaige** [comment]
@andamasov This should probably go to vyos.dev ; as we get closer to finishing the updates in this round, we should look to restructure the docs as a feature.
